# Generated by Django 5.1.4 on 2025-01-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecording',
            name='transcript',
            field=models.TextField(blank=True, help_text='The text transcribed from the audio recording.', null=True, verbose_name='Transcript'),
        ),
    ]
