# Generated by Django 5.1.4 on 2025-01-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_userrecording_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecording',
            name='highlighted_article',
            field=models.TextField(blank=True, help_text='The HTML content of the highlighted article.', null=True, verbose_name='Highlighted Article'),
        ),
        migrations.AddField(
            model_name='userrecording',
            name='highlighted_transcript',
            field=models.TextField(blank=True, help_text='The HTML content of the highlighted transcript.', null=True, verbose_name='Highlighted Transcript'),
        ),
    ]
